kind: Service
apiVersion: v1
metadata:
  name: cloud-syno
spec:
  ports:
    - name: cloud-syno
      protocol: TCP
      port: 5000
      targetPort: 5000
---
kind: Endpoints
apiVersion: v1
metadata:
  name: cloud-syno
subsets:
  - addresses:
      - ip: "{{ .Values.RedirectIP_Cloud }}"
    ports:
      - port: 5000
        name: cloud-syno        
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  name: cloud-syno
spec:
  tls:
  - hosts:
    - "{{ .Values.FQDN_Cloud }}"
    secretName: tls-secret
  rules:
  - host: "{{ .Values.FQDN_Cloud }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cloud-syno
            port:
              number: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: home-syno
spec:
  ports:
    - name: home-syno
      protocol: TCP
      port: 5000
      targetPort: 5000
---
kind: Endpoints
apiVersion: v1
metadata:
  name: home-syno
subsets:
  - addresses:
      - ip: "{{ .Values.RedirectIP_Home }}"
    ports:
      - port: 5000
        name: home-syno
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  name: home-syno
spec:
  tls:
  - hosts:
    - "{{ .Values.FQDN_Home }}"
    secretName: tls-secret
  rules:
  - host: "{{ .Values.FQDN_Home }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: home-syno
            port:
              number: 5000